spring.application.name=introduction
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

#db connection
spring.datasource.url=jdbc:mysql://localhost:3306/prod_ready_features
spring.datasource.username=root
spring.datasource.password=shipra123

#security configs
spring.security.user.name=ship
spring.security.user.password=pass
spring.security.user.roles=ADMIN

jwt.secretKey = ads98hbbds7uuhdfarhdbuw90jhbdweertysdec71b

